pyodbc.cpython-311-aarch64-linux-gnu.so,sha256=zWcq86ZagTJkKRM1shyY8SBcyZC-6PGdsxOUAW9FHk0,923657
pyodbc-5.0.0a2.dist-info/RECORD,,
pyodbc-5.0.0a2.dist-info/WHEEL,sha256=vWlGwhdECC9wcTU6fbest1U_zFWdeiQSqPWexEYEoQo,154
pyodbc-5.0.0a2.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0a2.dist-info/METADATA,sha256=rmKkah_waYVn7-pIvd_Nu8DsAeuAQxTTAVQpJ9DZKlw,2431
pyodbc-5.0.0a2.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-5.0.0a2.data/data/pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
